[versions]
agp = "8.13.2"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
espressoCore = "3.7.0"
junitVersion = "1.3.0"
material = "1.12.0"
# app
app-main = "7.4.0"
app-sdk-compile = "36"
app-sdk-min = "31"
app-sdk-target = "36"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-test-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espressoCore" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
google-material = { module = "com.google.android.material:material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
